#include "codegen.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>

CodeGenerator* codegen_create(IRModule* module, FILE* output) {
    CodeGenerator* generator = (CodeGenerator*)malloc(sizeof(CodeGenerator));
    if (!generator) {
        return NULL;
    }

    generator->module = module;
    generator->output = output;
    generator->indent_level = 0;
    generator->had_error = false;
    generator->error_message = NULL;

    return generator;
}

void codegen_free(CodeGenerator* generator) {
    if (generator) {
        if (generator->error_message) {
            free(generator->error_message);
        }
        free(generator);
    }
}

void codegen_emit_indent(CodeGenerator* generator) {
    if (!generator) return;

    for (int i = 0; i < generator->indent_level; i++) {
        fprintf(generator->output, "    ");
    }
}

void codegen_emit(CodeGenerator* generator, const char* format, ...) {
    if (!generator || !generator->output) return;

    va_list args;
    va_start(args, format);
    vfprintf(generator->output, format, args);
    va_end(args);
}

void codegen_emit_line(CodeGenerator* generator, const char* format, ...) {
    if (!generator || !generator->output) return;

    codegen_emit_indent(generator);

    va_list args;
    va_start(args, format);
    vfprintf(generator->output, format, args);
    va_end(args);

    fprintf(generator->output, "\n");
}

const char* codegen_c_type_from_ir(IRValueType type) {
    switch (type) {
        case IR_VALUE_INT:
            return "long";
        case IR_VALUE_FLOAT:
            return "double";
        case IR_VALUE_STRING:
            return "char*";
        case IR_VALUE_BOOLEAN:
            return "bool";
        case IR_VALUE_REGISTER:
        case IR_VALUE_TEMP:
            return "long"; // Default to long for registers
        case IR_VALUE_LABEL:
            return "void*";
        default:
            return "void";
    }
}

bool codegen_generate_c_header(CodeGenerator* generator) {
    if (!generator) return false;

    codegen_emit_line(generator, "// Generated by CodeTime compiler");
    codegen_emit_line(generator, "#include <stdio.h>");
    codegen_emit_line(generator, "#include <stdlib.h>");
    codegen_emit_line(generator, "#include <stdbool.h>");
    codegen_emit_line(generator, "");
    codegen_emit_line(generator, "// Runtime support");
    codegen_emit_line(generator, "void print_string(const char* s) {");
    generator->indent_level++;
    codegen_emit_line(generator, "printf(\"%%s\", s);");
    generator->indent_level--;
    codegen_emit_line(generator, "}");
    codegen_emit_line(generator, "");
    codegen_emit_line(generator, "void print_number(long n) {");
    generator->indent_level++;
    codegen_emit_line(generator, "printf(\"%%ld\", n);");
    generator->indent_level--;
    codegen_emit_line(generator, "}");
    codegen_emit_line(generator, "");
    codegen_emit_line(generator, "void print_decimal(double d) {");
    generator->indent_level++;
    codegen_emit_line(generator, "printf(\"%%f\", d);");
    generator->indent_level--;
    codegen_emit_line(generator, "}");
    codegen_emit_line(generator, "");
    codegen_emit_line(generator, "void print_boolean(bool b) {");
    generator->indent_level++;
    codegen_emit_line(generator, "printf(b ? \"true\" : \"false\");");
    generator->indent_level--;
    codegen_emit_line(generator, "}");
    codegen_emit_line(generator, "");

    return true;
}

bool codegen_generate_c_instruction(CodeGenerator* generator, IRInstruction* instruction) {
    if (!generator || !instruction) return false;

    switch (instruction->type) {
        case IR_NOP:
            codegen_emit_line(generator, "// nop");
            break;

        case IR_CONST: {
            if (instruction->result && instruction->operand1) {
                const char* type = codegen_c_type_from_ir(instruction->result->type);
                codegen_emit(generator, "%s ", type);

                if (instruction->result->type == IR_VALUE_REGISTER) {
                    codegen_emit(generator, "r%ld", instruction->result->data.register_number);
                } else {
                    codegen_emit(generator, "temp");
                }

                codegen_emit(generator, " = ");

                switch (instruction->operand1->type) {
                    case IR_VALUE_INT:
                        codegen_emit(generator, "%ld", instruction->operand1->data.int_value);
                        break;
                    case IR_VALUE_FLOAT:
                        codegen_emit(generator, "%f", instruction->operand1->data.float_value);
                        break;
                    case IR_VALUE_STRING:
                        codegen_emit(generator, "\"%s\"", instruction->operand1->data.string_value);
                        break;
                    case IR_VALUE_BOOLEAN:
                        codegen_emit(generator, "%s", instruction->operand1->data.bool_value ? "true" : "false");
                        break;
                    default:
                        codegen_emit(generator, "0");
                        break;
                }

                codegen_emit_line(generator, ";");
            }
            break;
        }

        case IR_LOAD: {
            if (instruction->result) {
                const char* type = codegen_c_type_from_ir(instruction->result->type);
                codegen_emit(generator, "%s ", type);

                if (instruction->result->type == IR_VALUE_REGISTER) {
                    codegen_emit(generator, "r%ld", instruction->result->data.register_number);
                }

                codegen_emit_line(generator, " = 0; // TODO: implement load");
            }
            break;
        }

        case IR_STORE: {
            codegen_emit_line(generator, "// TODO: implement store");
            break;
        }

        case IR_ADD:
        case IR_SUB:
        case IR_MUL:
        case IR_DIV:
        case IR_MOD: {
            if (instruction->result && instruction->operand1 && instruction->operand2) {
                const char* type = codegen_c_type_from_ir(instruction->result->type);
                codegen_emit(generator, "%s ", type);

                if (instruction->result->type == IR_VALUE_REGISTER) {
                    codegen_emit(generator, "r%ld", instruction->result->data.register_number);
                }

                codegen_emit(generator, " = ");

                if (instruction->operand1->type == IR_VALUE_REGISTER) {
                    codegen_emit(generator, "r%ld", instruction->operand1->data.register_number);
                } else {
                    codegen_emit(generator, "/* TODO: operand */");
                }

                const char* op;
                switch (instruction->type) {
                    case IR_ADD: op = "+"; break;
                    case IR_SUB: op = "-"; break;
                    case IR_MUL: op = "*"; break;
                    case IR_DIV: op = "/"; break;
                    case IR_MOD: op = "%"; break;
                    default: op = "+"; break;
                }

                codegen_emit(generator, " %s ", op);

                if (instruction->operand2->type == IR_VALUE_REGISTER) {
                    codegen_emit(generator, "r%ld", instruction->operand2->data.register_number);
                } else {
                    codegen_emit(generator, "/* TODO: operand */");
                }

                codegen_emit_line(generator, ";");
            }
            break;
        }

        case IR_NEG: {
            if (instruction->result && instruction->operand1) {
                const char* type = codegen_c_type_from_ir(instruction->result->type);
                codegen_emit(generator, "%s ", type);

                if (instruction->result->type == IR_VALUE_REGISTER) {
                    codegen_emit(generator, "r%ld", instruction->result->data.register_number);
                }

                codegen_emit(generator, " = -");

                if (instruction->operand1->type == IR_VALUE_REGISTER) {
                    codegen_emit(generator, "r%ld", instruction->operand1->data.register_number);
                }

                codegen_emit_line(generator, ";");
            }
            break;
        }

        case IR_CALL: {
            codegen_emit_line(generator, "// TODO: implement function call");
            break;
        }

        case IR_RETURN: {
            if (instruction->result) {
                codegen_emit(generator, "return ");

                if (instruction->result->type == IR_VALUE_REGISTER) {
                    codegen_emit(generator, "r%ld", instruction->result->data.register_number);
                } else if (instruction->result->type == IR_VALUE_INT) {
                    codegen_emit(generator, "%ld", instruction->result->data.int_value);
                } else if (instruction->result->type == IR_VALUE_BOOLEAN) {
                    codegen_emit(generator, "%s", instruction->result->data.bool_value ? "true" : "false");
                }

                codegen_emit_line(generator, ";");
            } else {
                codegen_emit_line(generator, "return;");
            }
            break;
        }

        case IR_JUMP: {
            codegen_emit_line(generator, "// TODO: implement jump");
            break;
        }

        case IR_JUMP_IF: {
            codegen_emit_line(generator, "// TODO: implement conditional jump");
            break;
        }

        case IR_LABEL: {
            if (instruction->result && instruction->result->type == IR_VALUE_LABEL) {
                codegen_emit_line(generator, "%s:", instruction->result->data.label_name);
            }
            break;
        }

        case IR_PARAM: {
            codegen_emit_line(generator, "// TODO: implement parameter");
            break;
        }

        case IR_PHI: {
            codegen_emit_line(generator, "// TODO: implement phi node");
            break;
        }

        default:
            codegen_emit_line(generator, "// Unknown instruction");
            break;
    }

    return true;
}

bool codegen_generate_c_basic_block(CodeGenerator* generator, IRBasicBlock* block) {
    if (!generator || !block) return false;

    if (block->name) {
        codegen_emit_line(generator, "%s:", block->name);
    }

    generator->indent_level++;

    IRInstruction* instr = block->instructions;
    while (instr) {
        codegen_generate_c_instruction(generator, instr);
        instr = instr->next;
    }

    generator->indent_level--;

    return true;
}

bool codegen_generate_c_function(CodeGenerator* generator, IRFunction* function) {
    if (!generator || !function) return false;

    // Function signature
    codegen_emit(generator, "long %s(", function->name ? function->name : "unnamed");

    // Parameters
    for (size_t i = 0; i < function->parameter_count; i++) {
        if (i > 0) {
            codegen_emit(generator, ", ");
        }
        codegen_emit(generator, "long param%zu", i);
    }

    codegen_emit_line(generator, ") {");

    generator->indent_level++;

    // Register declarations
    int max_reg = 0;
    IRBasicBlock* block = function->blocks;
    while (block) {
        IRInstruction* instr = block->instructions;
        while (instr) {
            if (instr->result && instr->result->type == IR_VALUE_REGISTER) {
                if (instr->result->data.register_number > max_reg) {
                    max_reg = instr->result->data.register_number;
                }
            }
            instr = instr->next;
        }
        block = block->next;
    }

    for (int i = 0; i <= max_reg; i++) {
        codegen_emit_line(generator, "long r%d;", i);
    }

    codegen_emit_line(generator, "");

    // Generate basic blocks
    block = function->blocks;
    while (block) {
        codegen_generate_c_basic_block(generator, block);
        block = block->next;
    }

    generator->indent_level--;
    codegen_emit_line(generator, "}");
    codegen_emit_line(generator, "");

    return true;
}

bool codegen_generate_c(CodeGenerator* generator) {
    if (!generator || !generator->module) return false;

    // Generate header
    codegen_generate_c_header(generator);

    // Generate functions
    IRFunction* func = generator->module->functions;
    while (func) {
        codegen_generate_c_function(generator, func);
        func = func->next;
    }

    // Generate main function if not present
    codegen_emit_line(generator, "int main() {");
    generator->indent_level++;
    codegen_emit_line(generator, "// Call entry point");
    codegen_emit_line(generator, "return 0;");
    generator->indent_level--;
    codegen_emit_line(generator, "}");

    return true;
}

bool codegen_generate(CodeGenerator* generator) {
    if (!generator) return false;

    return codegen_generate_c(generator);
}
